### ISSUE TITLE
Broken links for prepared databases

### ISSUE THREAD

**Issue by vmikk** [sourmash-bio/database-releases#2]
Hello!
I've tried to download prepared sourmash databases, but some links are broken at
https://sourmash.readthedocs.io/en/latest/databases.html#gtdb-r07-rs207-genomic-representatives-66k
E.g., none of the files are available for **GTDB R07-RS207 genomic representatives (66k).**

I'm sorry if it's not the right place to report this issue.

**Comment by ctb** [comment]
thank you for noticing! we serve the files from our HPC and it's down for another 24 hours 😭 

https://github.com/sourmash-bio/sourmash/issues/2325

**Comment by ctb** [comment]
It's back up! Give it a try!
